name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf  # v2.3.0
      with:
        swift-version: '6.1'
    
    - name: Cache Swift dependencies
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-swift-${{ hashFiles('Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-
    
    - name: Build
      run: swift build
    
    - name: Run tests
      run: swift test

  lint:
    name: Lint
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf  # v2.3.0
      with:
        swift-version: '6.1'
    
    - name: Cache Swift dependencies
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-swift-${{ hashFiles('Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-
    
    - name: Run SwiftLint
      run: make lint

  format-check:
    name: Format Check
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf  # v2.3.0
      with:
        swift-version: '6.1'
    
    - name: Cache Swift dependencies
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-swift-${{ hashFiles('Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-
    
    - name: Check code formatting
      run: make format-check